### ISSUE TITLE
Problem executing maven install

### ISSUE THREAD

**Issue by juanmanuelz** [codenvy/che-plugins#32]
Hi, thanks a lot for your work. It seems like there is a problem with the build of plugin-java. The generated plugin-java/che-plugin-java-runner-webapps/target/antrun/build-main.xml seems to have some problems. Here is the error:
**[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (prepare-tomcat-bundle) on project che-plugin-java-runner-webapps: An Ant BuildException has occured: /myworkspace/labs/che-plugins/plugin-java/che-plugin-java-runner-webapps/target/classes/apache-tomcat-7.0.54 does not exist.
[ERROR] around Ant part ...<move todir="/myworkspace/labs/che-plugins/plugin-java/che-plugin-java-runner-webapps/target/classes/tomcat-bundle">... @ 9:125 in /myworkspace/labs/che-plugins/plugin-java/che-plugin-java-runner-webapps/target/antrun/build-main.xml**

This happen because the unzipped tomcat file didn't have a apache-tomcat-7.0.54 as zip root entry. So the files got unzipped directly into the classes folder. 
As a temporary workaround I replaced the ant task configuration in the plugin-java/che-plugin-java-runner-webapps/pom.xml:
```<configuration>
    <tasks>
        <!-- Create folder for later  unzipped tomcat files-->
        <mkdir dir="${project.build.directory}/classes/tomcat-bundle"/>
       <!-- Unzip Tomcat package -->
        <unzip dest="${project.build.directory}/classes/tomcat-bundle" src="${project.build.directory}/classes/tomcat.zip">
            <patternset>
                <exclude name="**/webapps/**" />
            </patternset>
        </unzip>
        <!-- this move command is not longer necessary because the files are already there -->
        <!--move todir="${project.build.directory}/classes/tomcat-bundle">
            <fileset dir="${project.build.directory}/classes/apache-tomcat-${org.apache.tomcat.version}" />
        </move-->
        <delete file="${project.build.directory}/classes/tomcat.zip" />
        <!-- Zip prepared Tomcat binary distribution and remove temporary directory -->
        <zip basedir="${project.build.directory}/classes/tomcat-bundle" destfile="${project.build.directory}/classes/tomcat.zip" />
        <delete dir="${project.build.directory}/classes/tomcat-bundle" />
    </tasks>
</configuration>
```
Also I had to do the same with the plugin-sdk/che-plugin-sdk-runner/pom.xml
After the changes the error was gone.

I understand that I can solve the problem by changing the tomcat.zip structure.

**Comment by vparfonov** [comment]
Thanks for your suggest. Fix in https://github.com/codenvy/che-plugins/commit/977448a79d0c0ad37a09cee500e5723172b1d920
