### ISSUE TITLE
che-plugin-python-ext-python:3.12.5 build error

### ISSUE THREAD

**Issue by jjyr** [codenvy/che-plugins#450]
Downloaded: http://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0.15/plexus-utils-3.0.15.jar (234 KB at 174.1 KB/sec)
[INFO] Installing /home/user/che-3.13.4.2/ext/che-plugin-python-ext-python-3.12.5.jar to /home/user/.m2/repository/org/eclipse/che/plugin/che-plugin-python-ext-python/3.12.5/che-plugin-python-ext-python-3.12.5.jar
[INFO] Installing /tmp/mvninstall7852205763717972699.pom to /home/user/.m2/repository/org/eclipse/che/plugin/che-plugin-python-ext-python/3.12.5/che-plugin-python-ext-python-3.12.5.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.310 s
[INFO] Finished at: 2015-12-08T02:14:56+00:00
[INFO] Final Memory: 7M/180M
[INFO] ------------------------------------------------------------------------
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Extension found org.eclipse.che.plugin:che-plugin-python-ext-python:3.12.5
Including GWT module org.eclipse.che.ide.ext.python.Python
Found: 1 extension(s)
[INFO] Scanning for projects...
[INFO] Downloading: http://repo.maven.apache.org/maven2/org/eclipse/che/ide/che-ide-parent/3.13.4.2/che-ide-parent-3.13.4.2.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR] 
[ERROR] The project org.eclipse.che.ide:assembly-sdk-war:[unknown-version] (/home/user/che-3.13.4.2/sdk-resources/temp/pom.xml) has 1 error
[ERROR] Non-resolvable parent POM: Could not find artifact org.eclipse.che.ide:che-ide-parent:pom:3.13.4.2 in central (http://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Build of che assembly failed

**Comment by TylerJewell** [comment]
Hari:

You have run into an issue where the plug-in version that you are deploying
was compiled for a different version of Che.  We don't -- yet -- support
different plug-in versions even if the API set hasn't change.  I can see
that you are running Che 3.13.4.2 which has been released on the nightly
channel, but it hasn't yet shipped (and thus why our provided plug-ins are
pointing to 3.12.5.2).  You can see in the plug-in JAR that it's compiled
for the currently shipping version.

The easiest fix - do you have any way to install the 3.12.5.2 branch of
Che?  If you built Che from source, you can just checkout this version and
"mvn clean install".  Then your plug-in will deploy properly.

The other way, and it's a bit trickier is to get the plug-in compiled for
your version of Che.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by jjyr** [comment]
https://hub.docker.com/r/codenvy/che/
I use this docker image run che, and the only version this repo provide is 'latest'.
There should have more version tags than 'latest'.

**Comment by TylerJewell** [comment]
Funny, yes, we just wrote a specification on this very topic this morning.

1. We will have nightly images with a :nightly tag.
2. We will have a latest image.
3. We will have images with version tags.

I think it will not take long for us to have this activated. We already
have our CI system doing the builds, but just need to get it wired up to
Docker Hub.

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by eivantsov** [comment]
Did you try to build Python plugin alone? You mentioned a Docker image - are you doing it inside the image?

Or were you trying to include this plugin to Che assembly?

**Comment by jjyr** [comment]
@eivantsov  I just follow document drag python extension to che dashboard then click the 'stage' and 'build assembly' button

**Comment by TylerJewell** [comment]
@jjyr Yes, this is our issue right now.  The plug-in links on the drag-n-drop are for the 3.12.x version of Che and you are running a later version.  We have some work to do on insuring that the plug-ins are compatible across different compiled versions.  There are some open tickets on this.  

Unfortunately, for now to fix this, you need to build che-plugins repository against the same tag that you are building Che.  So I recommend:
1. git clone http://github.com/codenvy/che-plugins
2. git checkout 3.14.4.4
3. mvn clean install

1. git clone http://github.com/codenvy/che
2. git checkout 3.14.4.4
3. mvn clean install

You can then drag and drop the JAR files produced in the che-plugins repostitory into your Che instance.  We are huddling now internally on how to make our docs more consistent to avoid this issue.

**Comment by TylerJewell** [comment]
Please feel free to reopen this issue on github.com/codenvy/che. We are consolidating issues for Che into a single repository for simpler management.

A new Che 4.0 extension development guide has been posted.  It doesn't have the drag and drop yet, but you can now add extensions and build new assemblies with them.
https://eclipse-che.readme.io/v4.0/docs/developing-extensions
