### ISSUE TITLE
How to use the java debugger

### ISSUE THREAD

**Issue by moatazelmasry2** [codenvy/che-plugins#67]
Hi all,

In codeenvy I can see that the "java debugger" plugin is installed, but I can't find nowhere where/how to use a debugger and set breakpoints. Is that possible at all?

**Comment by TylerJewell** [comment]
Hi, yes it is possible.  We bury the instructions in our docs (not good!)
 we'll be making this more obvious.

http://docs.codenvy.com/user/technology-specific-features/#java

But you must launch a debug session, and then you can set breakpoints.  We
know we can make this easier and more obvious.

We will be working on making this a lot simpler soon.



Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55
